import type { AnnouncementUpsertInput } from "@/lib/platform/announcements/types";
import {
  JOIN_CONTEST_BY_GAME,
  JOIN_THE_CONTEST,
  PLATFORM_TERMS,
} from "@/lib/platform/legacy/competitiveLanguage";

export interface AnnouncementPreset {
  slug: string;
  name: string;
  description: string;
  payload: AnnouncementUpsertInput;
}

export const BUILTIN_ANNOUNCEMENT_PRESETS: AnnouncementPreset[] = [
  {
    slug: "live-trial-launch",
    name: "Live Trial Launch",
    description: "Top banner for the first-20 public live trial.",
    payload: {
      title: "SquareBoards Live Trial — Now Open",
      subtitle: "First 20 sign-ups · Real money · Start on $1 boards",
      displayType: "top_banner",
      category: "promotion",
      audience: "all",
      buttonText: "Join Trial",
      destinationHref: "/my-games/login",
      priorityLevel: "critical",
      frequency: "always",
      animationStyle: "fade",
      dismissible: true,
      active: true,
    },
  },
  {
    slug: "nfl-week-open",
    name: "NFL Week Opens",
    description: "Full-screen promo when a new NFL Pick'em week goes live.",
    payload: {
      title: "NFL Week is Open",
      subtitle: "Make your picks before kickoff — every tier, fully automated.",
      displayType: "welcome_popup",
      category: "nfl_week_open",
      audience: "all",
      buttonText: JOIN_CONTEST_BY_GAME.pickem,
      destinationHref: "/pickem/week",
      secondaryButtonText: PLATFORM_TERMS.browseLiveContests,
      secondaryDestinationHref: "/boards",
      priorityLevel: "high",
      frequency: "once",
      animationStyle: "scale",
      dismissible: true,
      active: true,
    },
  },
  {
    slug: "monday-night-football",
    name: "Monday Night Football",
    description: "Game day live event banner for MNF.",
    payload: {
      title: "Monday Night Football",
      subtitle: "Final picks lock at kickoff — tiebreaker may apply.",
      displayType: "live_event_banner",
      category: "monday_tiebreaker",
      audience: "pickem_players",
      buttonText: "View Picks",
      destinationHref: "/pickem/week",
      priorityLevel: "critical",
      frequency: "daily",
      animationStyle: "slide_up",
      dismissible: true,
      active: true,
    },
  },
  {
    slug: "holiday-giveaway",
    name: "Holiday Giveaway",
    description: "Seasonal full-screen promo with dual CTAs.",
    payload: {
      title: "Holiday Giveaway",
      subtitle: "Squares and Pick'em are live all weekend.",
      displayType: "welcome_popup",
      category: "holiday",
      audience: "all",
      buttonText: JOIN_THE_CONTEST,
      destinationHref: "/",
      secondaryButtonText: "Learn More",
      secondaryDestinationHref: "/pickem",
      priorityLevel: "high",
      frequency: "once",
      animationStyle: "scale",
      dismissible: true,
      active: true,
    },
  },
  {
    slug: "feature-release",
    name: "New Feature Release",
    description: "Hero + popup combo for platform updates.",
    payload: {
      title: "New on SquareBoards",
      subtitle: "Discover what's new this season.",
      displayType: "welcome_popup",
      category: "feature_release",
      audience: "returning_players",
      buttonText: "Explore",
      destinationHref: "/",
      priorityLevel: "normal",
      frequency: "once",
      animationStyle: "fade",
      dismissible: true,
      active: true,
    },
  },
  {
    slug: "maintenance-notice",
    name: "Maintenance Notice",
    description: "Top banner for scheduled downtime.",
    payload: {
      title: "Scheduled Maintenance",
      subtitle: "Brief downtime tonight — games resume automatically.",
      displayType: "top_banner",
      category: "maintenance",
      audience: "all",
      priorityLevel: "critical",
      frequency: "always",
      animationStyle: "fade",
      dismissible: false,
      active: true,
    },
  },
  {
    slug: "weekly-promotion",
    name: "Weekly Promotion",
    description: "Floating toast for returning players.",
    payload: {
      title: "This Week on SquareBoards",
      subtitle: "New boards and Pick'em pools are filling fast.",
      displayType: "floating_toast",
      category: "promotion",
      audience: "returning_players",
      buttonText: "Browse Games",
      destinationHref: "/boards",
      priorityLevel: "normal",
      frequency: "weekly",
      animationStyle: "slide_up",
      dismissible: true,
      active: true,
    },
  },
  {
    slug: "jackpot-winner",
    name: "Jackpot Winner",
    description: "Celebrate a big winner with a hero banner.",
    payload: {
      title: "Jackpot Winner",
      subtitle: "Congratulations to this week's champion.",
      displayType: "homepage_hero",
      category: "personalized",
      audience: "all",
      buttonText: "Hall of Fame",
      destinationHref: "/pickem/hall-of-fame",
      priorityLevel: "high",
      frequency: "daily",
      animationStyle: "fade",
      dismissible: false,
      active: true,
    },
  },
  {
    slug: "referral-bonus",
    name: "Referral Bonus",
    description: "Invite friends promo for new visitors.",
    payload: {
      title: "Join SquareBoards",
      subtitle: "Classic sports games — no experience required.",
      displayType: "welcome_popup",
      category: "promotion",
      audience: "anonymous",
      buttonText: "Get Started",
      destinationHref: "/boards",
      secondaryButtonText: "How It Works",
      secondaryDestinationHref: "/#how-it-works",
      priorityLevel: "normal",
      frequency: "once",
      animationStyle: "scale",
      dismissible: true,
      active: true,
    },
  },
];
