import type { ComplianceAlert, ComplianceAuditEntry } from "./types";

export const MOCK_COMPLIANCE_ALERTS: ComplianceAlert[] = [
  {
    id: "alert-fl-none",
    stateId: "FL",
    stateName: "Florida",
    title: "No active compliance alerts",
    description: "Florida jurisdiction operating within all compliance thresholds.",
    severity: "info",
    date: "2026-06-28T08:00:00Z",
    source: "Compliance Monitor",
    status: "resolved",
    recommendedAction: "No action required — continue standard monitoring.",
  },
  {
    id: "alert-tx-leg",
    stateId: "TX",
    stateName: "Texas",
    title: "Legislative update — skill contest bill",
    description:
      "Texas HB 2847 advances to committee. Potential impact on paid contest definitions. Monitor for Q3 session outcomes.",
    severity: "warning",
    date: "2026-06-25T14:30:00Z",
    source: "Legal Intelligence",
    status: "pending_legal",
    recommendedAction: "Prepare launch strategy documentation. Do not enable paid contests until legal approval.",
  },
  {
    id: "alert-ca-opinion",
    stateId: "CA",
    stateName: "California",
    title: "Attorney General opinion pending",
    description:
      "CA DOJ requested additional platform documentation. Opinion on skill-based contest classification expected within 60 days.",
    severity: "warning",
    date: "2026-06-20T11:00:00Z",
    source: "State Regulatory Feed",
    status: "open",
    recommendedAction: "Monitor legal developments. Maintain waitlist-only mode. Schedule legal review checkpoint.",
  },
  {
    id: "alert-ny-audit",
    stateId: "NY",
    stateName: "New York",
    title: "Quarterly compliance audit completed",
    description:
      "NY DFS-style audit cycle completed with zero findings. KYC and geo-fencing controls validated.",
    severity: "info",
    date: "2026-06-18T16:45:00Z",
    source: "Internal Audit",
    status: "resolved",
    recommendedAction: "Archive audit report. Schedule next review for Q3 2026.",
  },
  {
    id: "alert-co-review",
    stateId: "CO",
    stateName: "Colorado",
    title: "Internal compliance review in progress",
    description: "Colorado expansion dossier under executive review. Payment processor alignment pending.",
    severity: "info",
    date: "2026-06-22T09:15:00Z",
    source: "Ops Compliance",
    status: "open",
    recommendedAction: "Complete payment processor questionnaire. Await admin approval before status change.",
  },
  {
    id: "alert-nj-kyc",
    stateId: "NJ",
    stateName: "New Jersey",
    title: "Enhanced KYC threshold review",
    description: "NJ regulatory guidance suggests elevated verification for prize pools above $10K.",
    severity: "warning",
    date: "2026-06-24T13:00:00Z",
    source: "Compliance Engine",
    status: "pending_legal",
    recommendedAction: "Needs Legal Review — evaluate KYC tier adjustments for NJ launch.",
  },
  {
    id: "alert-ut-block",
    stateId: "UT",
    stateName: "Utah",
    title: "Jurisdiction unavailable — waitlist active",
    description: "Paid contests disabled pending legal clearance. Waitlist enrollment growing.",
    severity: "critical",
    date: "2026-06-15T10:00:00Z",
    source: "Geo Compliance",
    status: "open",
    recommendedAction: "Maintain disabled status. Track waitlist metrics for expansion planning.",
  },
];

export const MOCK_AUDIT_LOG: ComplianceAuditEntry[] = [
  {
    id: "audit-1",
    timestamp: "2026-06-28T09:12:00Z",
    actor: "Sarah Chen",
    action: "Reviewed",
    stateId: "NY",
    details: "NY quarterly audit marked resolved — no findings.",
  },
  {
    id: "audit-2",
    timestamp: "2026-06-27T15:40:00Z",
    actor: "Marcus Webb",
    action: "Flagged",
    stateId: "TX",
    details: "Legislative update flagged for legal review — no status change.",
  },
  {
    id: "audit-3",
    timestamp: "2026-06-26T11:05:00Z",
    actor: "Elena Rodriguez",
    action: "Noted",
    stateId: "CA",
    details: "CA opinion pending — waitlist mode confirmed, no auto-enable.",
  },
  {
    id: "audit-4",
    timestamp: "2026-06-25T08:30:00Z",
    actor: "James Okonkwo",
    action: "Approved",
    stateId: "FL",
    details: "Florida inventory increase recommendation approved (UI only).",
  },
  {
    id: "audit-5",
    timestamp: "2026-06-24T14:22:00Z",
    actor: "Priya Sharma",
    action: "Rejected",
    stateId: "UT",
    details: "Early launch proposal rejected — legal review incomplete.",
  },
  {
    id: "audit-6",
    timestamp: "2026-06-23T10:18:00Z",
    actor: "Sarah Chen",
    action: "Needs Legal Review",
    stateId: "NJ",
    details: "NJ KYC threshold change escalated to legal counsel.",
  },
];
